"""
Demo data for fallback mode when the backend is unavailable.
Provides a complete demo experience with Santhiya's pre-built profile.
"""
from typing import Dict, List

DEMO_USER = {
    "user_id": 1,
    "name": "Santhiya",
    "career_goal": "AI Engineer",
    "experience_level": "Intermediate",
    "learning_style": "Project-based",
    "weekly_hours": 10.0,
    "timeline_months": 6,
    "target_skills": ["Python", "Machine Learning", "Deep Learning", "NLP",
                       "Transformers", "Embeddings", "RAG", "AI Agents", "LLM", "Generative AI"],
    "readiness_score": 46.0,
    "skills": [
        {"skill_name": "Python", "current_proficiency": 80, "target_proficiency": 95, "gap": 15, "gap_category": "Minor Gap"},
        {"skill_name": "SQL", "current_proficiency": 50, "target_proficiency": 60, "gap": 10, "gap_category": "Minor Gap"},
        {"skill_name": "Machine Learning", "current_proficiency": 45, "target_proficiency": 85, "gap": 40, "gap_category": "Moderate Gap"},
        {"skill_name": "Deep Learning", "current_proficiency": 20, "target_proficiency": 95, "gap": 75, "gap_category": "Major Gap"},
        {"skill_name": "NLP", "current_proficiency": 10, "target_proficiency": 85, "gap": 75, "gap_category": "Major Gap"},
        {"skill_name": "Transformers", "current_proficiency": 5, "target_proficiency": 95, "gap": 90, "gap_category": "Major Gap"},
        {"skill_name": "Embeddings", "current_proficiency": 0, "target_proficiency": 95, "gap": 95, "gap_category": "Major Gap"},
        {"skill_name": "RAG", "current_proficiency": 0, "target_proficiency": 95, "gap": 95, "gap_category": "Major Gap"},
        {"skill_name": "AI Agents", "current_proficiency": 0, "target_proficiency": 95, "gap": 95, "gap_category": "Major Gap"},
        {"skill_name": "LLM", "current_proficiency": 5, "target_proficiency": 95, "gap": 90, "gap_category": "Major Gap"},
        {"skill_name": "Generative AI", "current_proficiency": 5, "target_proficiency": 95, "gap": 90, "gap_category": "Major Gap"},
        {"skill_name": "Statistics", "current_proficiency": 35, "target_proficiency": 70, "gap": 35, "gap_category": "Moderate Gap"},
        {"skill_name": "NumPy", "current_proficiency": 60, "target_proficiency": 85, "gap": 25, "gap_category": "Minor Gap"},
        {"skill_name": "Pandas", "current_proficiency": 55, "target_proficiency": 70, "gap": 15, "gap_category": "Minor Gap"},
    ]
}

DEMO_SKILL_GAP = {
    "user_id": 1,
    "readiness_score": 46.0,
    "priority_skills": ["Embeddings", "RAG", "AI Agents", "LLM", "Transformers"],
    "skill_gaps": DEMO_USER["skills"],
}

DEMO_RECOMMENDATIONS = [
    {
        "resource_id": "C016",
        "title": "Machine Learning Fundamentals",
        "description": "Supervised unsupervised learning regression classification and model evaluation",
        "resource_type": "Course",
        "skills": ["Machine Learning"],
        "difficulty": "Beginner",
        "duration_hours": 35,
        "rating": 4.9,
        "final_score": 91.0,
        "explanation": "Machine Learning is a high-priority skill for your AI Engineer goal. Your current proficiency is 45%, while the target proficiency is 85%. You already satisfy the Python prerequisite.",
        "matched_skills": ["Machine Learning"],
        "missing_prerequisites": [],
        "satisfied_prerequisites": ["Python", "Statistics"],
        "score_breakdown": {"skill_gap_match": 92, "goal_relevance": 88, "prerequisite_fit": 100, "difficulty_fit": 100, "preference_match": 80, "feedback_score": 72},
    },
    {
        "resource_id": "C027",
        "title": "Transformers & Attention Mechanism",
        "description": "Self-attention multi-head attention and the Transformer architecture from scratch",
        "resource_type": "Course",
        "skills": ["Transformers"],
        "difficulty": "Intermediate",
        "duration_hours": 30,
        "rating": 4.9,
        "final_score": 89.0,
        "explanation": "Transformers is critical for your AI Engineer goal with a 90-point gap. This course directly addresses your target skills for RAG and AI Agents.",
        "matched_skills": ["Transformers", "Deep Learning"],
        "missing_prerequisites": ["Deep Learning"],
        "satisfied_prerequisites": ["NLP"],
        "score_breakdown": {"skill_gap_match": 95, "goal_relevance": 92, "prerequisite_fit": 60, "difficulty_fit": 100, "preference_match": 80, "feedback_score": 72},
    },
    {
        "resource_id": "C033",
        "title": "RAG Foundations: Retrieval-Augmented Generation",
        "description": "Core concepts of RAG architecture retrieval augmentation and generation",
        "resource_type": "Course",
        "skills": ["RAG"],
        "difficulty": "Intermediate",
        "duration_hours": 22,
        "rating": 4.9,
        "final_score": 88.5,
        "explanation": "RAG is your #1 target skill as an aspiring AI Engineer. This foundational course builds the knowledge you need to eventually build real RAG applications.",
        "matched_skills": ["RAG", "Embeddings"],
        "missing_prerequisites": ["Embeddings", "Transformers"],
        "satisfied_prerequisites": [],
        "score_breakdown": {"skill_gap_match": 98, "goal_relevance": 96, "prerequisite_fit": 30, "difficulty_fit": 100, "preference_match": 80, "feedback_score": 72},
    },
    {
        "resource_id": "C039",
        "title": "AI Agents & Agentic Systems",
        "description": "ReAct tool use memory and orchestration of autonomous AI agents",
        "resource_type": "Course",
        "skills": ["AI Agents"],
        "difficulty": "Intermediate",
        "duration_hours": 25,
        "rating": 4.9,
        "final_score": 87.0,
        "explanation": "AI Agents is a core skill for your AI Engineer goal. This course teaches the ReAct pattern, tool use, and agent orchestration that power modern AI applications.",
        "matched_skills": ["AI Agents", "LLM"],
        "missing_prerequisites": ["LLM", "RAG"],
        "satisfied_prerequisites": [],
        "score_breakdown": {"skill_gap_match": 96, "goal_relevance": 95, "prerequisite_fit": 20, "difficulty_fit": 100, "preference_match": 80, "feedback_score": 72},
    },
    {
        "resource_id": "C021",
        "title": "Deep Learning with PyTorch",
        "description": "Neural network fundamentals CNNs RNNs and training with PyTorch",
        "resource_type": "Course",
        "skills": ["Deep Learning"],
        "difficulty": "Intermediate",
        "duration_hours": 40,
        "rating": 4.9,
        "final_score": 85.5,
        "explanation": "Deep Learning underpins Transformers, NLP, and Generative AI — all your target skills. Your current proficiency is 20%, and this course will take you to the Intermediate level.",
        "matched_skills": ["Deep Learning"],
        "missing_prerequisites": [],
        "satisfied_prerequisites": ["Machine Learning"],
        "score_breakdown": {"skill_gap_match": 90, "goal_relevance": 88, "prerequisite_fit": 80, "difficulty_fit": 100, "preference_match": 80, "feedback_score": 72},
    },
]

DEMO_LEARNING_PATH = {
    "user_id": 1,
    "career_goal": "AI Engineer",
    "total_phases": 8,
    "total_hours": 286,
    "estimated_weeks": 28,
    "estimated_months": 7,
    "readiness_score": 46.0,
    "phases": [
        {"phase": 1, "skill": "Machine Learning", "status": "in_progress", "gap_category": "Moderate Gap", "is_unlocked": True},
        {"phase": 2, "skill": "Deep Learning", "status": "available", "gap_category": "Major Gap", "is_unlocked": True},
        {"phase": 3, "skill": "NLP", "status": "locked", "gap_category": "Major Gap", "is_unlocked": False},
        {"phase": 4, "skill": "Transformers", "status": "locked", "gap_category": "Major Gap", "is_unlocked": False},
        {"phase": 5, "skill": "Embeddings", "status": "locked", "gap_category": "Major Gap", "is_unlocked": False},
        {"phase": 6, "skill": "LLM", "status": "locked", "gap_category": "Major Gap", "is_unlocked": False},
        {"phase": 7, "skill": "RAG", "status": "locked", "gap_category": "Major Gap", "is_unlocked": False},
        {"phase": 8, "skill": "AI Agents", "status": "locked", "gap_category": "Major Gap", "is_unlocked": False},
    ],
    "path_items": [
        {"order": 1, "phase": 1, "skill": "Machine Learning", "resource_type": "Course", "resource_id": "C016", "resource_title": "Machine Learning Fundamentals", "status": "in_progress", "is_milestone": False, "estimated_hours": 35, "recommendation_score": 91.0, "explanation": "Foundational ML course that builds your core competency needed for Deep Learning and AI.", "prerequisites": [], "missing_prerequisites": []},
        {"order": 2, "phase": 1, "skill": "Machine Learning", "resource_type": "Assessment", "resource_id": "ASSESS_ML", "resource_title": "Machine Learning Assessment", "status": "available", "is_milestone": True, "estimated_hours": 1, "recommendation_score": 0, "explanation": "Validate ML mastery before proceeding.", "prerequisites": ["Machine Learning"], "missing_prerequisites": []},
        {"order": 3, "phase": 1, "skill": "Machine Learning", "resource_type": "Project", "resource_id": "P002", "resource_title": "Movie Recommendation Engine", "status": "available", "is_milestone": False, "estimated_hours": 25, "recommendation_score": 82.0, "explanation": "Apply ML concepts in a real recommendation system.", "prerequisites": [], "missing_prerequisites": []},
        {"order": 4, "phase": 2, "skill": "Deep Learning", "resource_type": "Course", "resource_id": "C021", "resource_title": "Deep Learning with PyTorch", "status": "locked", "is_milestone": False, "estimated_hours": 40, "recommendation_score": 85.5, "explanation": "Build neural networks using PyTorch.", "prerequisites": ["Machine Learning"], "missing_prerequisites": ["Machine Learning"]},
        {"order": 5, "phase": 2, "skill": "Deep Learning", "resource_type": "Assessment", "resource_id": "ASSESS_DL", "resource_title": "Deep Learning Assessment", "status": "locked", "is_milestone": True, "estimated_hours": 1, "recommendation_score": 0, "explanation": "Validate DL mastery.", "prerequisites": ["Deep Learning"], "missing_prerequisites": ["Deep Learning"]},
        {"order": 6, "phase": 3, "skill": "NLP", "resource_type": "Course", "resource_id": "C025", "resource_title": "Natural Language Processing Fundamentals", "status": "locked", "is_milestone": False, "estimated_hours": 25, "recommendation_score": 84.0, "explanation": "Core NLP skills needed for Transformers and LLMs.", "prerequisites": ["Deep Learning", "Python"], "missing_prerequisites": ["Deep Learning"]},
        {"order": 7, "phase": 4, "skill": "Transformers", "resource_type": "Course", "resource_id": "C027", "resource_title": "Transformers & Attention Mechanism", "status": "locked", "is_milestone": False, "estimated_hours": 30, "recommendation_score": 89.0, "explanation": "Core architecture of all modern LLMs.", "prerequisites": ["Deep Learning", "NLP"], "missing_prerequisites": ["Deep Learning", "NLP"]},
        {"order": 8, "phase": 5, "skill": "Embeddings", "resource_type": "Course", "resource_id": "C031", "resource_title": "Sentence Transformers & Dense Retrieval", "status": "locked", "is_milestone": False, "estimated_hours": 20, "recommendation_score": 87.0, "explanation": "Dense embeddings power semantic search and RAG systems.", "prerequisites": ["Transformers"], "missing_prerequisites": ["Transformers"]},
        {"order": 9, "phase": 6, "skill": "LLM", "resource_type": "Course", "resource_id": "C036", "resource_title": "LLM Fundamentals: How Large Language Models Work", "status": "locked", "is_milestone": False, "estimated_hours": 20, "recommendation_score": 86.0, "explanation": "Understand how GPT, Gemini, and LLMs work.", "prerequisites": ["Transformers"], "missing_prerequisites": ["Transformers"]},
        {"order": 10, "phase": 7, "skill": "RAG", "resource_type": "Course", "resource_id": "C033", "resource_title": "RAG Foundations: Retrieval-Augmented Generation", "status": "locked", "is_milestone": False, "estimated_hours": 22, "recommendation_score": 88.5, "explanation": "Build real RAG applications.", "prerequisites": ["Embeddings", "LLM"], "missing_prerequisites": ["Embeddings", "LLM"]},
        {"order": 11, "phase": 8, "skill": "AI Agents", "resource_type": "Course", "resource_id": "C039", "resource_title": "AI Agents & Agentic Systems", "status": "locked", "is_milestone": False, "estimated_hours": 25, "recommendation_score": 87.0, "explanation": "Build autonomous AI agent systems.", "prerequisites": ["RAG", "LLM"], "missing_prerequisites": ["RAG", "LLM"]},
    ]
}

DEMO_DASHBOARD = {
    "user_id": 1,
    "name": "Santhiya",
    "career_goal": "AI Engineer",
    "readiness_score": 46.0,
    "current_phase": "Phase 1: Machine Learning",
    "next_action": "Start: Machine Learning Fundamentals",
    "overall_completion": 12.0,
    "courses_completed": 0,
    "projects_completed": 0,
    "assessments_taken": 0,
    "skills_mastered": [],
    "recent_activity": [],
}
